### ISSUE TITLE
Fix OSMPbfDownloader

### ISSUE THREAD

**Issue by RaczeQ** [kraina-ai/srai#366]
Protomaps service is getting deprecated - we have to deprecate it as well and replace it with Geofabrik as the default.

**Comment by bdon** [comment]
Hi, just letting you know we are improving this service with a proper JSON API instead of browser forms, and likely also changing the URL in the near future.

**Comment by RaczeQ** [comment]
That's amazing! We're looking forward to it then 😄 Thanks for the heads-up.
